version: '3.7'

services:
  news_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  news_web:
    build: .
    image: peaceful_shirley
    command: bash -c "python /usr/src/news/manage.py makemigrations &&
             python /usr/src/news/manage.py migrate --noinput &&
             python /usr/src/news/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/news
    ports:
      - 8000:8000
    depends_on:
      - news_db

volumes:
  postgres_data:
